final List<String> items = List.generate(100, (index) => 'Item ${index + 1}');
final List<Hotel> hotels = [
  Hotel(id: 1, name: 'Pan Pacific Hotel Sonargaon', address: 'Kazi Nazrul Islam Aveniu Dhaka', rating: 6.0, price: 16000, description: 'Pan Pacific Hotels Group is a member of Singapore-listed UOL Group Limited, one of Asia’s most established hotel and property companies with an outstanding portfolio of investment and development properties. Pan Pacific Sonargaon Dhaka welcomes you with a warm heart to enjoy the typical five-star facilities available; from first class surroundings to world-class hospitality in true Pan Pacific style, right from the airport. Pan Pacific Hotels Group is a member of Singapore-listed UOL Group Limited, one of Asia’s most established hotel and property companies with an outstanding portfolio of investment and development properties. Pan Pacific Sonargaon Dhaka welcomes you with a warm heart to enjoy the typical five-star facilities available; from first class surroundings to world-class hospitality in true Pan Pacific style, right from the airport.', image: 'images/sonargaon.jpg'),
  Hotel(id: 2, name: 'Six Seasons Hotel', address: 'Nr 96 House Nr 19 Road Gulshan 2, Dhaka City 1212 Bangladesh', rating: 5.0, price: 6000, description: 'Even before the shovel first hit the ground to build the hotels foundation, we had one goal in mind- to provide unrivaled luxury for all of our guests. We put in the finest amenities and facilities in our hotel, and we have also included some awe-inspiring sights. As the project progressed, it slowly dawned on us- not only have we offered the ultimate luxury in the Bangladeshi hospitality industry, we have also offered the finest facilities in all of the Indian Subcontinent. We have included many Bangladeshi firsts - heated, salt water, and best of all, hanging, and partially transparent, infinity pool, a 119 feet tall mosaic mural, and a state-of-the-art heating and water filtration system for the whole building. To that we have added jaw-dropping features- glass floor on our Sky Pool Bar, a spectacular rooftop private dining room, and some mouth-watering culinary options, among them a live Teppanyaki show and a sushi bar. Six Seasons is an extraordinary hotel that offers every indulgence. With per room expenditure matching or exceeding ultra-luxury hotels chains around the world, you would not expect any less than the finest. At Six Seasons Hotel, we redefine luxury. Even before the shovel first hit the ground to build the hotels foundation, we had one goal in mind- to provide unrivaled luxury for all of our guests. We put in the finest amenities and facilities in our hotel, and we have also included some awe-inspiring sights. As the project progressed, it slowly dawned on us- not only have we offered the ultimate luxury in the Bangladeshi hospitality industry, we have also offered the finest facilities in all of the Indian Subcontinent. We have included many Bangladeshi firsts - heated, salt water, and best of all, hanging, and partially transparent, infinity pool, a 119 feet tall mosaic mural, and a state-of-the-art heating and water filtration system for the whole building. To that we have added jaw-dropping features- glass floor on our Sky Pool Bar, a spectacular rooftop private dining room, and some mouth-watering culinary options, among them a live Teppanyaki show and a sushi bar. Six Seasons is an extraordinary hotel that offers every indulgence. With per room expenditure matching or exceeding ultra-luxury hotels chains around the world, you would not expect any less than the finest. At Six Seasons Hotel, we redefine luxury.', image: 'images/six_sejon.jpg'),
  Hotel(id: 3, name: 'Sea Pearl Beach Resort & Spa Coxs Bazar', address: 'Jaliapalong, Inani, Ukhia, Coxs Bazar 4750 Bangladesh', rating: 5.0, price: 5000, description: 'Located on worlds longest undivided coastline - Coxs Bazar. > Largest Eco Resort located on Inani Beach - Excellent coral viewing. > All rooms have sea view with a choice of balcony and kitchenettes > Multiple Food & Beverage outlets serving local and international flavors > Kids water park, Ice Cream Parlour, Gaming Parlour, Mocktail Bar > Parasailing, Snorkeling, Speed Boat, Virtual Golf Located on worlds longest undivided coastline - Coxs Bazar. > Largest Eco Resort located on Inani Beach - Excellent coral viewing. > All rooms have sea view with a choice of balcony and kitchenettes > Multiple Food & Beverage outlets serving local and international flavors > Kids water park, Ice Cream Parlour, Gaming Parlour, Mocktail Bar > Parasailing, Snorkeling, Speed Boat, Virtual Golf Located on worlds longest undivided coastline - Coxs Bazar. > Largest Eco Resort located on Inani Beach - Excellent coral viewing. > All rooms have sea view with a choice of balcony and kitchenettes > Multiple Food & Beverage outlets serving local and international flavors > Kids water park, Ice Cream Parlour, Gaming Parlour, Mocktail Bar > Parasailing, Snorkeling, Speed Boat, Virtual Golf', image: 'images/sea_pearl.jpg'),
  Hotel(id: 4, name: 'Radisson Blu Chattogram Bay View', address: 'SS Khaled Road Lalkhan Bazar, Chittagong City 4000 Bangladesh', rating: 8.0, price: 7000, description: 'As the city’s premiere upscale international hotel, the Radisson Blu Chattogram Bay View offers guests an unforgettable lodging experience in Chattogram. Stay within walking distance of M. A. Aziz Stadium and Chattogram Club Limited in this commercial capital, and enjoy proximity to popular destinations like Cox’s Bazar. The hotel lies just a 10-minute drive from the city’s business hub and 40 minutes from Shah Amanat International Airport (CGP). Our 241 rooms and suites offer modern style and thoughtful amenities, including free high-speed, wireless Internet and coffee and tea facilities. Start your morning with our complimentary Super Breakfast buffet, then head to one of our numerous restaurants and bars for lunch or dinner to savor international cuisine, freshly pressed juices and classic cocktails. After a full day of meetings, unwind with a swim in our circular infinity pool, a refreshing beverage from the pool bar or a therapeutic treatment at the spa. As the city’s premiere upscale international hotel, the Radisson Blu Chattogram Bay View offers guests an unforgettable lodging experience in Chattogram. Stay within walking distance of M. A. Aziz Stadium and Chattogram Club Limited in this commercial capital, and enjoy proximity to popular destinations like Cox’s Bazar. The hotel lies just a 10-minute drive from the city’s business hub and 40 minutes from Shah Amanat International Airport (CGP). Our 241 rooms and suites offer modern style and thoughtful amenities, including free high-speed, wireless Internet and coffee and tea facilities. Start your morning with our complimentary Super Breakfast buffet, then head to one of our numerous restaurants and bars for lunch or dinner to savor international cuisine, freshly pressed juices and classic cocktails. After a full day of meetings, unwind with a swim in our circular infinity pool, a refreshing beverage from the pool bar or a therapeutic treatment at the spa.', image: 'images/radison_blue.jpg'),
  Hotel(id: 5, name: 'Radisson Blu Dhaka Water Garden', address: 'Airport Road, Dhaka Cantonment, Dhaka City 1206 Bangladesh', rating: 7.0, price: 5000, description: 'Finding an ideal family-friendly hotel in Dhaka City does not have to be difficult. Welcome to Radisson Blu Dhaka Water Garden, a nice option for travelers like you As your “home away from home,” the hotel rooms offer a flat screen TV, air conditioning, and a minibar, and getting online is easy, with free wifi available.Guests have access to room service and a concierge while staying at Radisson Blu Dhaka Water Garden. In addition, Radisson Dhaka offers a pool and a poolside bar, which will help make your Dhaka City trip additionally gratifying. And, as an added convenience, there is free parking available to guests. Given the close proximity to Chawkbazar Shahi Mosque (1.7 mi), guests of Radisson Blu Dhaka Water Garden can easily experience one of Dhaka Citys most popular landmarks. During your visit, be sure to check out a popular Dhaka City bibimbap restaurant such as Koreana Restaurant, which is a short distance from Radisson Blu Dhaka Water Garden. Dhaka City is also known for some great military museums, including Liberation War Museum and Bangladesh air force museum, which are not too far from Radisson Dhaka. Radisson Blu Dhaka Water Garden puts the best of Dhaka City at your fingertips, making your stay both relaxing and enjoyable. Finding an ideal family-friendly hotel in Dhaka City does not have to be difficult. Welcome to Radisson Blu Dhaka Water Garden, a nice option for travelers like you As your “home away from home,” the hotel rooms offer a flat screen TV, air conditioning, and a minibar, and getting online is easy, with free wifi available.Guests have access to room service and a concierge while staying at Radisson Blu Dhaka Water Garden. In addition, Radisson Dhaka offers a pool and a poolside bar, which will help make your Dhaka City trip additionally gratifying. And, as an added convenience, there is free parking available to guests. Given the close proximity to Chawkbazar Shahi Mosque (1.7 mi), guests of Radisson Blu Dhaka Water Garden can easily experience one of Dhaka Citys most popular landmarks. During your visit, be sure to check out a popular Dhaka City bibimbap restaurant such as Koreana Restaurant, which is a short distance from Radisson Blu Dhaka Water Garden. Dhaka City is also known for some great military museums, including Liberation War Museum and Bangladesh air force museum, which are not too far from Radisson Dhaka. Radisson Blu Dhaka Water Garden puts the best of Dhaka City at your fingertips, making your stay both relaxing and enjoyable.', image: 'images/radison_blu_dhaka.jpg'),
];

class Hotel{
  int id;
  String name;
  String address;
  double rating;
  double price;
  String description;
  bool favorite;
  String image;

  Hotel({
    required this.id,
    required this.name,
    required this.address,
    required this.rating,
    required this.price,
    required this.description,
    this.favorite = false,
    required this.image});
}